version: '3.4'

services:  
  uruguay:    
    image: upload-site:latest
    environment:    
      - COUNTRY=URUGUAY 
    ports:
      - "8080:8080" 
  espana:    
    image: upload-site:latest
    environment:    
      - COUNTRY=ESPANA   
    ports:
      - "8081:8080"